wandb_version: 1

wandb:
  desc: null
  value:
    log: true
    entity: mssfj-1
    project: llmeval
    run_name: swallow-ms-7b-chatmath-merge-gpt4o
github_version:
  desc: null
  value: v2.0.0
testmode:
  desc: null
  value: false
api:
  desc: null
  value: false
model:
  desc: null
  value:
    use_wandb_artifacts: false
    artifacts_path: ''
    pretrained_model_name_or_path: /home/ubuntu/evol-merge/final_merge/
    trust_remote_code: true
    device_map: auto
    load_in_8bit: false
    load_in_4bit: false
generator:
  desc: null
  value:
    do_sample: false
    num_beams: 1
    top_p: 1.0
    top_k: 0
    temperature: 0.1
    repetition_penalty: 1.0
tokenizer:
  desc: null
  value:
    use_wandb_artifacts: false
    artifacts_path: ''
    pretrained_model_name_or_path: /home/ubuntu/evol-merge/final_merge/
    use_fast: false
max_seq_length:
  desc: null
  value: 2048
dataset_artifact:
  desc: null
  value: wandb-japan/llm-leaderboard/jaster:v11
dataset_dir:
  desc: null
  value: /jaster/1.2.6/evaluation/test
target_dataset:
  desc: null
  value: all
log_dir:
  desc: null
  value: ./logs
torch_dtype:
  desc: null
  value: bf16
custom_prompt_template:
  desc: null
  value: null
custom_fewshots_template:
  desc: null
  value: null
metainfo:
  desc: null
  value:
    basemodel_name: swallow-ms-7b-chatmath-gpt4o
    model_type: open llm
    instruction_tuning_method: None
    instruction_tuning_data:
    - None
    num_few_shots: 0
    llm-jp-eval-version: 1.1.0
mtbench:
  desc: null
  value:
    question_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_question:v0
    referenceanswer_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer:v0
    judge_prompt_artifacts_path: wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1
    bench_name: japanese_mt_bench
    model_id: null
    question_begin: null
    question_end: null
    max_new_token: 1024
    num_choices: 1
    num_gpus_per_model: 1
    num_gpus_total: 1
    max_gpu_memory: null
    dtype: bfloat16
    judge_model: gpt-4o-2024-05-13
    mode: single
    baseline_model: null
    parallel: 1
    first_n: null
    custom_conv_template: true
    conv_name: custom
    conv_system_template: '{system_message}'
    conv_system_message: 以下は、タスクを説明する指示と、文脈のある入力の組み合わせです。要求を適切に満たす応答を書きなさい。
    conv_roles: ('指示', '応答')
    conv_sep: '


      ### '
    conv_sep2: ''
    conv_stop_token_ids: '[2]'
    conv_stop_str: '###'
    conv_sep_style: custom
    conv_role_message_separator: ':

      '
    conv_role_only_separator: ':

      '
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722022979.333974
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 86
      - 95
      - 96
      - 97
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 86
      - 95
      - 96
      - 97
      - 98
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.16.0
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
