genome:
    models:
      - HachiML/Swallow-MS-7b-v0.1-ChatMathSkill
      - tokyotech-llm/Swallow-MS-7b-instruct-v0.1
    merge_method: linear
    layer_granularity: 4 # sane default
    allow_negative_weights: true # useful with task_arithmetic
tasks:
  - name: elyzatasks100
    weight: 1.0
